#Используем базовый образ с Alpine Linux для минимального размера
ARG ALPINE_VERSION=3.23
#--------------------------------Image--------------------------------
FROM alpine:${ALPINE_VERSION}
RUN set -ex; \
apk update && apk add --no-cache bash openrc openresolv iproute2 libqrencode p7zip

#Xray core
RUN mkdir /opt/xray/
RUN mkdir /opt/xray/config/
COPY /Containers/xray-core/Xray-linux-arm64-v8a.7z /opt/xray/xray.7z

#Xray service
COPY /Containers/init.d/xray /etc/init.d/xray
RUN chmod +x /etc/init.d/xray
RUN rc-update add xray default

COPY /Containers/start.sh /opt/start.sh
RUN chmod +x /opt/start.sh
RUN sed -i 's/\r//' /opt/start.sh

RUN sed -i 's/^tty/#tty/' /etc/inittab
ENTRYPOINT ["sh", "-c"]
CMD ["/bin/bash /opt/start.sh && /sbin/init"]

#https://github.com/XTLS/Xray-core
#https://github.com/xjasonlyu/tun2socks
